language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
script:
    - find ./project -name \*.py -exec pep8 --ignore=E402 {} +
    - coverage run project/test.py
after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
email: false